/**
 * Bridal Team — Supabase auth email templates.
 *
 * One shared shell, one file per template, so every email is provably identical
 * except for its copy and call-to-action. Run `node emails/build.mjs` to
 * regenerate the .html files after editing the CONTENT block below.
 *
 * Paste each generated file into Supabase Dashboard → Authentication →
 * Email Templates. Supabase template variables ({{ .ConfirmationURL }} etc.)
 * are preserved verbatim.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const OUT_DIR = dirname(fileURLToPath(import.meta.url));

// Brand constants — mirrors app/globals.css and the live site.
const LOGO = "https://bridalteam.com/icon-192.png";
const FONT_DISPLAY =
  "'Jost','Futura','Century Gothic','Segoe UI',Helvetica,Arial,sans-serif";
const FONT_BODY =
  "'Raleway',-apple-system,'Segoe UI',Helvetica,Arial,sans-serif";

/** The bulletproof CTA button (gradient + Outlook VML fallback). */
function button(label) {
  return `          <tr>
            <td class="bt-pad" align="center" style="padding:0 48px 8px 48px;">
              <!--[if mso]>
              <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{{ .ConfirmationURL }}" style="height:52px;v-text-anchor:middle;width:300px;" arcsize="50%" strokecolor="#f36705" fillcolor="#f36705">
                <w:anchorlock/>
                <center style="color:#ffffff;font-family:'Segoe UI',Helvetica,Arial,sans-serif;font-size:16px;font-weight:bold;">${label}</center>
              </v:roundrect>
              <![endif]-->
              <!--[if !mso]><!-- -->
              <a href="{{ .ConfirmationURL }}" target="_blank" style="display:inline-block;background-color:#f36705;background-image:linear-gradient(120deg,#ff8c1c 0%,#f36705 100%);color:#ffffff;font-family:${FONT_DISPLAY};font-size:16px;font-weight:600;letter-spacing:0.3px;line-height:52px;text-align:center;text-decoration:none;padding:0 44px;border-radius:26px;box-shadow:0 12px 26px -10px rgba(243,103,5,0.7);">
                ${label}
              </a>
              <!--<![endif]-->
            </td>
          </tr>

          <!-- Fallback link -->
          <tr>
            <td class="bt-pad" style="padding:26px 48px 34px 48px;">
              <p style="margin:0 0 8px 0;font-family:${FONT_BODY};font-size:13px;line-height:1.5;color:#7b7b7b;">
                Button not working? Copy and paste this link into your browser:
              </p>
              <p style="margin:0;font-family:${FONT_BODY};font-size:13px;line-height:1.5;word-break:break-all;">
                <a href="{{ .ConfirmationURL }}" target="_blank" style="color:#f36705;text-decoration:underline;">{{ .ConfirmationURL }}</a>
              </p>
            </td>
          </tr>`;
}

/** A one-time-code panel (for templates that verify with {{ .Token }}). */
function codePanel() {
  return `          <tr>
            <td class="bt-pad" align="center" style="padding:0 48px 34px 48px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 auto;">
                <tr>
                  <td align="center" style="background-color:#f4f4f4;border:1px solid #eaeaea;border-radius:14px;padding:20px 40px;">
                    <span style="font-family:${FONT_DISPLAY};font-size:38px;font-weight:600;letter-spacing:10px;color:#f36705;">{{ .Token }}</span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>`;
}

/**
 * Renders a complete email.
 * @param {{title,preheader,eyebrow,h1,body,cta,note,mode}} o
 * mode: "button" (default) or "code".
 */
function render(o) {
  const action = o.mode === "code" ? codePanel() : button(o.cta);
  return `<!--
  Bridal Team — Supabase Auth "${o.title}" email template.
  Paste into Supabase Dashboard → Authentication → Email Templates.
  Generated by emails/build.mjs — edit there, not here.
  Table layout + inline styles for cross-client support (Gmail, Apple Mail, Outlook).
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="color-scheme" content="light only" />
  <meta name="supported-color-schemes" content="light only" />
  <title>${o.title}</title>
  <!--[if mso]>
  <noscript><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml></noscript>
  <![endif]-->
  <style>
    body,table,td,a{-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;}
    table,td{mso-table-lspace:0pt;mso-table-rspace:0pt;}
    img{-ms-interpolation-mode:bicubic;border:0;height:auto;line-height:100%;outline:none;text-decoration:none;}
    body{margin:0;padding:0;width:100%!important;height:100%!important;}
    a{text-decoration:none;}
    @media only screen and (max-width:600px){
      .bt-container{width:100%!important;}
      .bt-pad{padding-left:26px!important;padding-right:26px!important;}
      .bt-h1{font-size:26px!important;}
    }
  </style>
</head>
<body style="margin:0;padding:0;background-color:#f4f4f4;">
  <div style="display:none;max-height:0;overflow:hidden;mso-hide:all;font-size:1px;line-height:1px;color:#f4f4f4;opacity:0;">
    ${o.preheader}
  </div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f4f4f4;">
    <tr>
      <td align="center" style="padding:32px 16px;">

        <!-- Card -->
        <table role="presentation" class="bt-container" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;background-color:#ffffff;border-radius:18px;overflow:hidden;box-shadow:0 18px 40px -18px rgba(34,34,34,0.20);">

          <!-- Brand header band -->
          <tr>
            <td align="center" style="background-color:#f36705;background-image:linear-gradient(120deg,#ff9000 0%,#ff8c1c 35%,#f36705 100%);padding:34px 40px 30px 40px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td style="padding-right:12px;" valign="middle">
                    <img src="${LOGO}" width="44" height="44" alt="Bridal Team" style="display:block;width:44px;height:44px;border-radius:11px;background:#ffffff;" />
                  </td>
                  <td valign="middle">
                    <span style="font-family:${FONT_DISPLAY};font-size:24px;font-weight:600;letter-spacing:0.5px;color:#ffffff;">Bridal Team</span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td class="bt-pad" style="padding:44px 48px 8px 48px;">
              <p style="margin:0 0 14px 0;font-family:${FONT_DISPLAY};font-size:12px;font-weight:600;letter-spacing:2.5px;text-transform:uppercase;color:#f36705;">
                ${o.eyebrow}
              </p>
              <h1 class="bt-h1" style="margin:0 0 18px 0;font-family:${FONT_DISPLAY};font-size:30px;line-height:1.2;font-weight:600;color:#222222;">
                ${o.h1}
              </h1>
              <p style="margin:0 0 30px 0;font-family:${FONT_BODY};font-size:16px;line-height:1.65;color:#303030;">
                ${o.body}
              </p>
            </td>
          </tr>

${action}

          <!-- Divider -->
          <tr>
            <td style="padding:0 48px;">
              <div style="border-top:1px solid #eaeaea;font-size:0;line-height:0;">&nbsp;</div>
            </td>
          </tr>

          <!-- Security note -->
          <tr>
            <td class="bt-pad" style="padding:24px 48px 40px 48px;">
              <p style="margin:0;font-family:${FONT_BODY};font-size:13px;line-height:1.6;color:#9c9c9d;">
                ${o.note}
              </p>
            </td>
          </tr>

        </table>
        <!-- /Card -->

        <!-- Footer -->
        <table role="presentation" class="bt-container" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;margin-top:20px;background-color:#222222;border-radius:18px;overflow:hidden;">
          <tr>
            <td class="bt-pad" align="center" style="padding:34px 48px 30px 48px;">
              <span style="font-family:${FONT_DISPLAY};font-size:20px;font-weight:600;letter-spacing:0.5px;color:#ffffff;">Bridal Team</span>
              <p style="margin:12px auto 0 auto;max-width:360px;font-family:${FONT_BODY};font-size:13px;line-height:1.6;color:rgba(255,255,255,0.6);">
                Fun, simple wedding planning — reimagined for today and powered by AI.
                Organize details, find ideas, and collaborate with your team.
              </p>

              <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:22px auto 0 auto;">
                <tr>
                  <td style="padding:0 6px;">
                    <a href="https://www.facebook.com/bridalteam" target="_blank" style="font-family:${FONT_BODY};font-size:12px;font-weight:600;letter-spacing:0.4px;color:#f5ad00;text-decoration:none;">Facebook</a>
                  </td>
                  <td style="color:rgba(255,255,255,0.25);">&bull;</td>
                  <td style="padding:0 6px;">
                    <a href="https://www.instagram.com/bridalteam" target="_blank" style="font-family:${FONT_BODY};font-size:12px;font-weight:600;letter-spacing:0.4px;color:#f5ad00;text-decoration:none;">Instagram</a>
                  </td>
                  <td style="color:rgba(255,255,255,0.25);">&bull;</td>
                  <td style="padding:0 6px;">
                    <a href="https://www.pinterest.com/bridalteam" target="_blank" style="font-family:${FONT_BODY};font-size:12px;font-weight:600;letter-spacing:0.4px;color:#f5ad00;text-decoration:none;">Pinterest</a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td style="padding:0 48px;">
              <div style="border-top:1px solid rgba(255,255,255,0.10);font-size:0;line-height:0;">&nbsp;</div>
            </td>
          </tr>
          <tr>
            <td class="bt-pad" align="center" style="padding:18px 48px 30px 48px;">
              <p style="margin:0;font-family:${FONT_BODY};font-size:12px;line-height:1.6;color:rgba(255,255,255,0.5);">
                &copy; Bridal Team. All rights reserved.<br />
                <a href="https://bridalteam.com" target="_blank" style="color:rgba(255,255,255,0.6);text-decoration:none;">bridalteam.com</a>
              </p>
            </td>
          </tr>
        </table>
        <!-- /Footer -->

      </td>
    </tr>
  </table>
</body>
</html>
`;
}

// ─── Per-template content ──────────────────────────────────────────────────
const TEMPLATES = {
  "confirm-signup": {
    title: "Confirm your email address",
    preheader:
      "You're one click away — confirm your email to finish setting up Bridal Team.",
    eyebrow: "Welcome to the team",
    h1: "Confirm your email address",
    body: "You're almost ready to start planning. Tap the button below to confirm this email address and finish setting up your Bridal Team account.",
    cta: "Confirm email address",
    note: "If you didn't create a Bridal Team account, you can safely ignore this email — no account will be created without confirmation.",
  },
  "magic-link": {
    title: "Your sign-in link",
    preheader: "Your secure, one-time link to sign in to Bridal Team.",
    eyebrow: "Your sign-in link",
    h1: "Sign in to Bridal Team",
    body: "Tap the button below to securely sign in — no password needed. For your safety, this link works once and expires shortly.",
    cta: "Sign in to Bridal Team",
    note: "If you didn't request this link, you can safely ignore this email — your account stays secure and no one can sign in without it.",
  },
  "reset-password": {
    title: "Reset your password",
    preheader: "Choose a new password for your Bridal Team account.",
    eyebrow: "Password reset",
    h1: "Reset your password",
    body: "We received a request to reset the password for your Bridal Team account. Tap the button below to choose a new one. This link expires shortly.",
    cta: "Reset password",
    note: "Didn't ask to reset your password? You can safely ignore this email — your current password will stay the same.",
  },
  invite: {
    title: "You're invited to Bridal Team",
    preheader: "You've been invited to collaborate on Bridal Team.",
    eyebrow: "You're invited",
    h1: "Join your team on Bridal Team",
    body: "You've been invited to help plan on Bridal Team. Accept your invitation below to create your account and start collaborating with your team.",
    cta: "Accept invitation",
    note: "If you weren't expecting this invitation, you can safely ignore this email — no account will be created without your action.",
  },
  "change-email": {
    title: "Confirm your email change",
    preheader: "Confirm the new email address for your Bridal Team account.",
    eyebrow: "Confirm your new email",
    h1: "Confirm your email change",
    body: "You asked to change the email address on your Bridal Team account to <strong style=\"color:#222222;\">{{ .NewEmail }}</strong>. Tap the button below to confirm the switch.",
    cta: "Confirm email change",
    note: "If you didn't request this change, you can safely ignore this email — your current email address will stay active until the new one is confirmed.",
  },
  reauthentication: {
    title: "Your verification code",
    preheader: "Your Bridal Team verification code.",
    eyebrow: "Verify it's you",
    h1: "Your verification code",
    body: "Enter the code below to confirm it's really you. For your safety, it expires shortly.",
    mode: "code",
    note: "If you didn't request this code, you can safely ignore this email — no changes will be made to your account.",
  },
};

for (const [name, cfg] of Object.entries(TEMPLATES)) {
  const html = render(cfg);
  writeFileSync(join(OUT_DIR, `${name}.html`), html, "utf8");
  console.log(`✓ ${name}.html`);
}
console.log(`\nGenerated ${Object.keys(TEMPLATES).length} templates in emails/`);
